Feat/search by name
RamonJales/bora-pagar-shippuden pull request #154
Opened 2024-09-11 23:19 UTC by DanilloFonseca

**Por favor, informe se a PR segue os requisitos obrigatórios:**
#146 

- [x] Mesmo padrão de código do projeto
- [ ] Arquivos alterados/adicionados seguem o padrão _Camel Case_
- [ ] A PR está relacionada a uma ou mais issue
- [x] Relacionei todas as issues na seção de "Development" da PR
- [ ] O código foi revisado uma vez ou mais
**Motivação para a criação da PR**

**O que foi feito**
Implementei o método para fazer busca pelo nome da matéria.

**O que faltou desenvolver**
Faltou elaborar melhor o método search, para retornar todas as disciplinas se o usuário não passar nenhum parâmetro.

2024-09-13 23:21 UTC, IanGabriel12 requested changes

2024-09-13 23:21 UTC, IanGabriel12 commented on backend/src/main/java/com/borathings/borapagar/subject/SubjectController.java
> +import org.springframework.web.bind.annotation.*;
Má prática. Importe apenas o que for usar

2024-09-13 23:21 UTC, IanGabriel12 commented on backend/pom.xml
> +    </dependencies>
Por que adicionar + uma dependência?

2025-01-28 18:30 UTC, joseemds commented
Fechando, porque iremos utilizar a API do SIGAA para isso

2025-01-28 18:30 UTC, closed without merging