feat: Adicionando handler de `BadRequestException`
RamonJales/bora-pagar-shippuden pull request #67
Opened 2024-07-25 19:54 UTC by IanGabriel12

**Por favor, informe se a PR segue os requisitos obrigatórios:**

- [x] Mesmo padrão de código do projeto
- [x] Arquivos alterados/adicionados seguem o padrão _Camel Case_
- [x] A PR está relacionada a uma ou mais issue
- [x] Relacionei todas as issues na seção de "Development" da PR
- [x] O código foi revisado uma vez ou mais

**Motivação para a criação da PR**

closes #63. Veja a motivação disso na issue.

**O que foi feito**

Adicionando handler de `BadRequestException` que será lançado por features futuras.

2024-08-09 10:50 UTC, Kywal requested changes

2024-08-09 10:50 UTC, Kywal commented on backend/src/main/java/com/borathings/borapagar/core/exception/GlobalExceptionHandler.java
> +    public ResponseEntity<Object> handleBadRequestExcpetion(BadRequestException ex) {
Typo no nome do método

2024-08-09 10:50 UTC, Kywal commented on backend/src/main/java/com/borathings/borapagar/core/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(BadRequestException.class)
Cadê o javadoc?

2024-08-20 12:25 UTC, isaacmsl commented on backend/src/main/java/com/borathings/borapagar/core/exception/GlobalExceptionHandler.java
> +    public ResponseEntity<Object> handleBadRequestExcpetion(BadRequestException ex) {
Resolvido

2024-08-20 12:31 UTC, isaacmsl approved these changes
LGTM

2024-08-21 20:06 UTC, IanGabriel12 commented
Isso é código morto e não há mais motivos para continuar desenvolvendo ele.

2024-08-21 20:06 UTC, closed without merging